export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
}

export enum ListingCategory {
  HOUSE = 'HOUSE',
  FLAT = 'FLAT',
  PG = 'PG',
  SHOP = 'SHOP',
  VILLA = 'VILLA',
  OFFICE = 'OFFICE',
  HOSTEL = 'HOSTEL',
  COWORKING = 'COWORKING',
  WAREHOUSE = 'WAREHOUSE',
  ROOMMATE = 'ROOMMATE',
  DORMITORY = 'DORMITORY',
  HOTEL = 'HOTEL',
  DHARAMSHALA = 'DHARAMSHALA',
  HOURLY_ROOM = 'HOURLY_ROOM',
  HOUSE_GUEST = 'HOUSE_GUEST',
  SHARE_STAY = 'SHARE_STAY',
}

export enum ListingStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  FROZEN = 'FROZEN',
}
